//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWithSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fruit
    {
        public int FruitKey { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public string Description { get; set; }
        public int Season { get; set; }
        public string RequestMsg { get; set; }
        public string ResponseMsg { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
