//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWithSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysAuth
    {
        public int ID { get; set; }
        public int TypeKey { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public bool IsSale { get; set; }
    }
}
